version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - "6500:5432"
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 427542
      POSTGRES_DB: mydb
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev.furkan@outlook.com
      PGADMIN_DEFAULT_PASSWORD: 427542
    volumes:
      - pgadmin4:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin4:     