basePath: /api
host: localhost:8080
info:
  contact: {}
  description: List APIs of User Book Management
  termsOfService: http://swagger.io/terms/
  title: User Library Management API Document
  version: "1.0"
paths: {}
swagger: "2.0"
